#!/bin/sh

image_name=`uci get oneapi.@main[0].image_name 2>/dev/null`

if [ "$image_name" == "oneapiinc/pms-docker:latest" -a "`uname -m`" != "x86_64" ]; then
    uci -q batch <<-EOF >/dev/null
        set oneapi.@main[0].image_name=""
        commit oneapi
EOF
fi
exit 0
